In [2]:
import numpy as np
import pandas as pd
import os
print(os.listdir())

['.ipynb_checkpoints', 'laptop.ipynb', 'laptop_price.csv', 'predictor.pickle']

In [45]:
data = pd.read_csv("laptop_price.csv",encoding="latin-1")
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [4]:
data.shape

(1303, 12)

In [5]:
data.info

<bound method DataFrame.info of       laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro
1             2   Apple                          Macbook Air
2             3      HP                               250 G6
3             4   Apple                          MacBook Pro
4             5   Apple                          MacBook Pro
...         ...     ...                                  ...
1298       1316  Lenovo                       Yoga 500-14ISK
1299       1317  Lenovo                       Yoga 900-13ISK
1300       1318  Lenovo                   IdeaPad 100S-14IBR
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600
1              Ultrabook    13.3                                    1440x900
2               Notebook    15.6                           Full HD 1920x1080
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600
...                  ...     ...                                         ...
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300            Notebook    14.0                                    1366x768
1301            Notebook    15.6                                    1366x768
1302            Notebook    15.6                                    1366x768

                                       Cpu   Ram  \
0                     Intel Core i5 2.3GHz   8GB
1                     Intel Core i5 1.8GHz   8GB
2               Intel Core i5 7200U 2.5GHz   8GB
3                     Intel Core i7 2.7GHz  16GB
4                     Intel Core i5 3.1GHz   8GB
...                                    ...   ...
1298            Intel Core i7 6500U 2.5GHz   4GB
1299            Intel Core i7 6500U 2.5GHz  16GB
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB
1301            Intel Core i7 6500U 2.5GHz   6GB
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB

                               Gpu       OpSys  Weight  Price_euros
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69
1           Intel HD Graphics 6000       macOS  1.34kg       898.94
2            Intel HD Graphics 620       No OS  1.86kg       575.00
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00
1300             Intel HD Graphics  Windows 10   1.5kg       229.00
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00
1302             Intel HD Graphics  Windows 10   2.2kg       369.00

[1303 rows x 12 columns]>

In [46]:
data['Ram'] = data['Ram'].astype('str').str.replace("GB","").astype('int32')
data['Weight'] = data['Weight'].astype('str').str.replace("kg","").astype('float32')

In [7]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [8]:
data.corr(numeric_only=True)['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [9]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [47]:
def add_company(inpt):
    if inpt == 'Samsung' or inpt == 'Razer' or inpt == 'Mediacom' or inpt == 'Microsoft'or inpt == 'Xiaomi'or inpt == 'Vero'or inpt == 'Chuwi'or inpt == 'Google'or inpt == 'Fujitsu'or inpt == 'LG'or inpt == 'Huawei':
        return 'Other'
    else:
        return inpt

In [48]:
data['Company'] = data['Company'].apply(add_company)

In [12]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [13]:
len(data['Product'].value_counts())

618

In [49]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['Ips'] = data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [15]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [50]:
data['cpu_name'] = data['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))

In [51]:
def set_processor(name):
    if name == 'Intel Core i7' or name == 'Intel Core i5' or name == 'Intel Core i3':
        return name
    else:
        if name.split()[0] == 'AMD':
            return 'AMD'
        else:
            return 'Other'

In [52]:
data['cpu_name'] = data['cpu_name'].apply(set_processor)

In [53]:
data['gpu_name'] = data['Gpu'].apply(lambda x:" ".join(x.split()[0:1]))

In [20]:
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [21]:
data.shape

(1303, 16)

In [54]:
data = data[data['gpu_name'] != 'ARM']

In [23]:
data.shape

(1302, 16)

In [24]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [55]:
def set_os(inpt):
    if inpt == 'Windows 10' or inpt == 'Windows 7' or inpt == 'Windows 10 S':
        return 'Windows'
    elif inpt == 'macOS' or inpt == 'Mac OS X':
        return 'Mac'
    elif inpt == 'Linux':
        return inpt
    else:
        return 'Other'

In [56]:
data['OpSys'] = data['OpSys'].apply(set_os)
data['OpSys'].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [57]:
data = data.drop(columns=['laptop_ID', 'Inches', 'Product', 'ScreenResolution', 'Cpu', 'Gpu'])

In [28]:
data.head()

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,Apple,Ultrabook,8,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,HP,Notebook,8,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,Apple,Ultrabook,16,Mac,1.83,2537.45,0,1,Intel Core i7,AMD
4,Apple,Ultrabook,8,Mac,1.37,1803.60,0,1,Intel Core i5,Intel

In [58]:
data = pd.get_dummies(data)

In [30]:
data.head(2)
data.shape

(1302, 32)

In [ ]:
!pip install sklearn

In [59]:
X = data.drop('Price_euros', axis=1)
y = data['Price_euros']
print(X.shape[1])

31

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [34]:
X_train.shape, X_test.shape

((976, 31), (326, 31))

In [61]:
def model_acc(model):
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(str(model)+ ' --> ' +str(acc))

In [62]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

LinearRegression() --> 0.7007856720936547
Lasso() --> 0.7088113360247057
DecisionTreeRegressor() --> 0.7240361441901463
RandomForestRegressor() --> 0.8154754549899714

Hyperparameter tunning

In [63]:
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(X_train, y_train)

best_model = grid_fit.best_estimator_
best_model

best_model.score(X_test, y_test)

0.8206605593516325

In [38]:
X_test.columns

Index(['Ram', 'Weight', 'Touchscreen', 'Ips', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_HP', 'Company_Lenovo',
       'Company_MSI', 'Company_Other', 'Company_Toshiba',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'OpSys_Linux', 'OpSys_Mac', 'OpSys_Other', 'OpSys_Windows',
       'cpu_name_AMD', 'cpu_name_Intel Core i3', 'cpu_name_Intel Core i5',
       'cpu_name_Intel Core i7', 'cpu_name_Other', 'gpu_name_AMD',
       'gpu_name_Intel', 'gpu_name_Nvidia'],
      dtype='object')

Save model

In [64]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [42]:
pred_value = best_model.predict([[8, 1.3, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,1,0 ]])
pred_value

c:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1495.2838])